SOURCES := \
	../pascal/src/tensor/add.c \
	../pascal/src/tensor/append.c \
	../pascal/src/tensor/clamp.c \
	../pascal/src/tensor/conv2d.c \
	../pascal/src/tensor/convolution.c \
	../pascal/src/tensor/copy.c \
	../pascal/src/tensor/diag.c \
	../pascal/src/tensor/divide.c \
	../pascal/src/tensor/dot.c \
	../pascal/src/tensor/expand_dims.c \
	../pascal/src/tensor/eye.c \
	../pascal/src/tensor/flatten.c \
	../pascal/src/tensor/free.c \
	../pascal/src/tensor/get.c \
	../pascal/src/tensor/init.c \
	../pascal/src/tensor/linspace.c \
	../pascal/src/tensor/linalg_inv.c \
	../pascal/src/tensor/linalg_solve.c \
	../pascal/src/tensor/linalg_cholesky.c \
	../pascal/src/tensor/linalg_triangular_solve.c \
	../pascal/src/tensor/map.c \
	../pascal/src/tensor/matmul.c \
	../pascal/src/tensor/max_pool.c \
	../pascal/src/tensor/mean_all.c \
	../pascal/src/tensor/multiply.c \
	../pascal/src/tensor/new.c \
	../pascal/src/tensor/new_no_malloc.c \
	../pascal/src/tensor/new_repeat.c \
	../pascal/src/tensor/ones.c \
	../pascal/src/tensor/print.c \
	../pascal/src/tensor/prod_all.c \
	../pascal/src/tensor/random_normal.c \
	../pascal/src/tensor/random_uniform.c \
	../pascal/src/tensor/reciprocal.c \
	../pascal/src/tensor/reshape.c \
	../pascal/src/tensor/scalar_multiply.c \
	../pascal/src/tensor/square.c \
	../pascal/src/tensor/subtract.c \
	../pascal/src/tensor/sum.c \
	../pascal/src/tensor/sum_all.c \
	../pascal/src/tensor/tile.c \
	../pascal/src/tensor/transpose.c \
	../pascal/src/tensor/uncertain_normal.c \
	../pascal/src/tensor/zeros.c \
	../pascal/src/tensor_random_sample/normal.c \
	../pascal/src/tensor_random_sample/uniform.c \
	../pascal/src/tensor_utils/tensor_binary_operate.c \
	../pascal/src/tensor_utils/tensor_print_shape.c\
	../pascal/src/tensor_utils/tensor_print_values.c \
	../pascal/src/tensor_utils/tensor_utils_apply_transpose_map.c \
	../pascal/src/tensor_utils/tensor_utils_default_stride.c \
	../pascal/src/tensor_utils/tensor_utils_get_convolution_array.c \
	../pascal/src/tensor_utils/tensor_utils_get_convolution_start_index.c \
	../pascal/src/tensor_utils/tensor_utils_get_masked_index.c \
	../pascal/src/tensor_utils/tensor_utils_get_masked_offset.c \
	../pascal/src/tensor_utils/tensor_utils_get_pointer.c \
	../pascal/src/tensor_utils/tensor_utils_index_from_linear_index.c \
	../pascal/src/tensor_utils/tensor_utils_index_from_linear_index_transpose_safe.c \
	../pascal/src/tensor_utils/tensor_utils_linalg_get_array_col_maj.c \
	../pascal/src/tensor_utils/tensor_utils_shapes_equal.c \
	../pascal/src/tensor_utils/tensor_utils_size_from_shape.c \
	../pascal/src/tensor_utils/tensor_utils_unary_chain_rule.c \
	../pascal/src/tensor_utils/tensor_utils_unravel.c \
	../pascal/src/tensor_utils/tensor_utils_unravel_and_replace.c \
	../pascal/src/tensor_broadcast/broadcast_output_free.c \
	../pascal/src/tensor_broadcast/broadcast_output_init.c \
	../pascal/src/tensor_broadcast/tensor_broadcast.c \
	../pascal/src/tensor_broadcast/tensor_broadcast_and_operate.c \
	../pascal/src/tensor_broadcast/tensor_broadcast_is_needed.c \
	../pascal/src/tensor_broadcast/tensor_broadcast_is_needed_linalg.c \
	../pascal/src/tensor_broadcast/tensor_broadcast_linalg.c \
	../pascal/src/tensor_broadcast/tensor_linear_index_from_index.c \
	../pascal/src/tensor_iterate/tensor_iterator_copy.c \
	../pascal/src/tensor_iterate/tensor_iterator_free.c \
	../pascal/src/tensor_iterate/tensor_iterator_new.c \
	../pascal/src/tensor_iterate/tensor_iterate.c \
	../pascal/src/tensor_iterate/tensor_iterate_current.c \
	../pascal/src/tensor_iterate/tensor_iterate_indexes_next.c \
	../pascal/src/tensor_iterate/tensor_iterate_next.c \
	../pascal/src/clapack/ddot.c \
	../pascal/src/clapack/dgemm.c \
	../pascal/src/clapack/dgemv.c \
	../pascal/src/clapack/dger.c \
	../pascal/src/clapack/dgesv.c \
	../pascal/src/clapack/dgetf2.c \
	../pascal/src/clapack/dgetrf.c \
	../pascal/src/clapack/dgetri.c \
	../pascal/src/clapack/dgetrs.c \
	../pascal/src/clapack/dlamch.c \
	../pascal/src/clapack/dlaswp.c\
	../pascal/src/clapack/dscal.c \
	../pascal/src/clapack/dswap.c \
	../pascal/src/clapack/dtrmm.c \
	../pascal/src/clapack/dtrmv.c \
	../pascal/src/clapack/dtrsm.c \
	../pascal/src/clapack/dtrti2.c \
	../pascal/src/clapack/dtrtri.c \
	../pascal/src/clapack/idamax.c \
	../pascal/src/clapack/ieeeck.c \
	../pascal/src/clapack/ilaenv.c \
	../pascal/src/clapack/iparmq.c \
	../pascal/src/clapack/lsame.c \
	../pascal/src/clapack/lsamen.c \
	../pascal/src/clapack/maxloc.c \
	../pascal/src/clapack/xerbla.c \
	../pascal/src/clapack/xerbla_array.c \
	../pascal/src/clapack/f2c/abort_.c \
	../pascal/src/clapack/f2c/backspac.c \
	../pascal/src/clapack/f2c/c_abs.c \
	../pascal/src/clapack/f2c/c_cos.c \
	../pascal/src/clapack/f2c/c_div.c \
	../pascal/src/clapack/f2c/c_exp.c \
	../pascal/src/clapack/f2c/c_log.c \
	../pascal/src/clapack/f2c/c_sin.c \
	../pascal/src/clapack/f2c/c_sqrt.c \
	../pascal/src/clapack/f2c/cabs.c \
	../pascal/src/clapack/f2c/close.c \
	../pascal/src/clapack/f2c/ctype.c \
	../pascal/src/clapack/f2c/d_abs.c \
	../pascal/src/clapack/f2c/d_acos.c \
	../pascal/src/clapack/f2c/d_asin.c \
	../pascal/src/clapack/f2c/d_atan.c \
	../pascal/src/clapack/f2c/d_atn2.c \
	../pascal/src/clapack/f2c/d_cnjg.c \
	../pascal/src/clapack/f2c/d_cos.c \
	../pascal/src/clapack/f2c/d_cosh.c \
	../pascal/src/clapack/f2c/d_dim.c \
	../pascal/src/clapack/f2c/d_exp.c \
	../pascal/src/clapack/f2c/d_imag.c \
	../pascal/src/clapack/f2c/d_int.c \
	../pascal/src/clapack/f2c/d_lg10.c \
	../pascal/src/clapack/f2c/d_log.c \
	../pascal/src/clapack/f2c/d_mod.c \
	../pascal/src/clapack/f2c/d_nint.c \
	../pascal/src/clapack/f2c/d_prod.c \
	../pascal/src/clapack/f2c/d_sign.c \
	../pascal/src/clapack/f2c/d_sin.c \
	../pascal/src/clapack/f2c/d_sinh.c \
	../pascal/src/clapack/f2c/d_sqrt.c \
	../pascal/src/clapack/f2c/d_tan.c \
	../pascal/src/clapack/f2c/d_tanh.c \
	../pascal/src/clapack/f2c/derf_.c \
	../pascal/src/clapack/f2c/derfc_.c \
	../pascal/src/clapack/f2c/dfe.c \
	../pascal/src/clapack/f2c/dolio.c \
	../pascal/src/clapack/f2c/dtime_.c \
	../pascal/src/clapack/f2c/due.c \
	../pascal/src/clapack/f2c/ef1asc_.c \
	../pascal/src/clapack/f2c/ef1cmc_.c \
	../pascal/src/clapack/f2c/endfile.c \
	../pascal/src/clapack/f2c/erf_.c \
	../pascal/src/clapack/f2c/erfc_.c \
	../pascal/src/clapack/f2c/err.c \
	../pascal/src/clapack/f2c/etime_.c \
	../pascal/src/clapack/f2c/exit_.c \
	../pascal/src/clapack/f2c/f77_aloc.c \
	../pascal/src/clapack/f2c/f77vers.c \
	../pascal/src/clapack/f2c/fmt.c \
	../pascal/src/clapack/f2c/fmtlib.c \
	../pascal/src/clapack/f2c/ftell_.c \
	../pascal/src/clapack/f2c/getenv_.c \
	../pascal/src/clapack/f2c/h_abs.c \
	../pascal/src/clapack/f2c/h_dim.c \
	../pascal/src/clapack/f2c/h_dnnt.c \
	../pascal/src/clapack/f2c/h_indx.c \
	../pascal/src/clapack/f2c/h_len.c \
	../pascal/src/clapack/f2c/h_mod.c \
	../pascal/src/clapack/f2c/h_nint.c \
	../pascal/src/clapack/f2c/h_sign.c \
	../pascal/src/clapack/f2c/hl_ge.c \
	../pascal/src/clapack/f2c/hl_gt.c \
	../pascal/src/clapack/f2c/hl_le.c \
	../pascal/src/clapack/f2c/hl_lt.c \
	../pascal/src/clapack/f2c/i77vers.c \
	../pascal/src/clapack/f2c/i_abs.c \
	../pascal/src/clapack/f2c/i_ceiling.c \
	../pascal/src/clapack/f2c/i_dim.c \
	../pascal/src/clapack/f2c/i_dnnt.c \
	../pascal/src/clapack/f2c/i_indx.c \
	../pascal/src/clapack/f2c/i_len.c \
	../pascal/src/clapack/f2c/i_len_trim.c \
	../pascal/src/clapack/f2c/i_mod.c \
	../pascal/src/clapack/f2c/i_nint.c \
	../pascal/src/clapack/f2c/i_sign.c \
	../pascal/src/clapack/f2c/iio.c \
	../pascal/src/clapack/f2c/ilnw.c \
	../pascal/src/clapack/f2c/inquire.c \
	../pascal/src/clapack/f2c/l_ge.c \
	../pascal/src/clapack/f2c/l_gt.c \
	../pascal/src/clapack/f2c/l_le.c \
	../pascal/src/clapack/f2c/l_lt.c \
	../pascal/src/clapack/f2c/lbitbits.c \
	../pascal/src/clapack/f2c/lbitshft.c \
	../pascal/src/clapack/f2c/lread.c \
	../pascal/src/clapack/f2c/lwrite.c \
	../pascal/src/clapack/f2c/open.c \
	../pascal/src/clapack/f2c/pow_ci.c \
	../pascal/src/clapack/f2c/pow_dd.c \
	../pascal/src/clapack/f2c/pow_di.c \
	../pascal/src/clapack/f2c/pow_hh.c \
	../pascal/src/clapack/f2c/pow_ii.c \
	../pascal/src/clapack/f2c/pow_ri.c \
	../pascal/src/clapack/f2c/pow_zi.c \
	../pascal/src/clapack/f2c/pow_zz.c \
	../pascal/src/clapack/f2c/r_abs.c \
	../pascal/src/clapack/f2c/r_acos.c \
	../pascal/src/clapack/f2c/r_asin.c \
	../pascal/src/clapack/f2c/r_atan.c \
	../pascal/src/clapack/f2c/r_atn2.c \
	../pascal/src/clapack/f2c/r_cnjg.c \
	../pascal/src/clapack/f2c/r_cos.c \
	../pascal/src/clapack/f2c/r_cosh.c \
	../pascal/src/clapack/f2c/r_dim.c \
	../pascal/src/clapack/f2c/r_exp.c \
	../pascal/src/clapack/f2c/r_imag.c \
	../pascal/src/clapack/f2c/r_int.c \
	../pascal/src/clapack/f2c/r_lg10.c \
	../pascal/src/clapack/f2c/r_log.c \
	../pascal/src/clapack/f2c/r_mod.c \
	../pascal/src/clapack/f2c/r_nint.c \
	../pascal/src/clapack/f2c/r_sign.c \
	../pascal/src/clapack/f2c/r_sin.c \
	../pascal/src/clapack/f2c/r_sinh.c \
	../pascal/src/clapack/f2c/r_sqrt.c \
	../pascal/src/clapack/f2c/r_tan.c \
	../pascal/src/clapack/f2c/r_tanh.c \
	../pascal/src/clapack/f2c/rdfmt.c \
	../pascal/src/clapack/f2c/rewind.c \
	../pascal/src/clapack/f2c/rsfe.c \
	../pascal/src/clapack/f2c/rsli.c \
	../pascal/src/clapack/f2c/rsne.c \
	../pascal/src/clapack/f2c/s_cat.c \
	../pascal/src/clapack/f2c/s_cmp.c \
	../pascal/src/clapack/f2c/s_copy.c \
	../pascal/src/clapack/f2c/s_paus.c \
	../pascal/src/clapack/f2c/s_rnge.c \
	../pascal/src/clapack/f2c/s_stop.c \
	../pascal/src/clapack/f2c/sfe.c \
	../pascal/src/clapack/f2c/sig_die.c \
	../pascal/src/clapack/f2c/signal_.c \
	../pascal/src/clapack/f2c/sue.c \
	../pascal/src/clapack/f2c/system_.c \
	../pascal/src/clapack/f2c/typesize.c \
	../pascal/src/clapack/f2c/uio.c \
	../pascal/src/clapack/f2c/util.c \
	../pascal/src/clapack/f2c/wref.c \
	../pascal/src/clapack/f2c/wrtfmt.c \
	../pascal/src/clapack/f2c/wsfe.c \
	../pascal/src/clapack/f2c/wsle.c \
	../pascal/src/clapack/f2c/wsne.c \
	../pascal/src/clapack/f2c/xwsne.c \
	../pascal/src/clapack/f2c/z_abs.c \
	../pascal/src/clapack/f2c/z_cos.c \
	../pascal/src/clapack/f2c/z_div.c \
	../pascal/src/clapack/f2c/z_exp.c \
	../pascal/src/clapack/f2c/z_log.c \
	../pascal/src/clapack/f2c/z_sin.c \
	../pascal/src/clapack/f2c/z_sqrt.c \
	main.c

CFLAGS = -I../pascal/include/
LDFLAGS	=
LIBS	=

CFLAGS+=-DUXHW -std=c99 -D_GNU_SOURCE -D_USE_MATH_DEFINES -DSYSDEP_H_INCLUDED
